/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEKeyDrivenNavigableItem.h"

@class DBGMemoryDataProcessWrapper, DBGViewDebuggerAdditionUIController, DVTObservingToken, NSArray, NSString;

@interface DBGProcessNavigableItem : IDEKeyDrivenNavigableItem
{
    NSArray *_cachedChildRepresentedObjects;
    NSArray *_queueContentArray;
    BOOL _hasFilterString;
    DBGMemoryDataProcessWrapper *_memoryDataGroup;
    DVTObservingToken *_viewDebuggerObservingToken;
    DVTObservingToken *_showOnlyInterestingViewObjectsObservingToken;
    DVTObservingToken *_showOnlyVisibleViewObjectsObservingToken;
    BOOL _showsCompressedStackFrames;
    BOOL _showsOnlyAncestorWithInterestingFrames;
    BOOL _showsPendingBlocks;
    int _navigatorContentMode;
    DBGViewDebuggerAdditionUIController *_viewDebuggingUIController;
    NSString *_filterString;
}

+ (id)keyPathsForValuesAffectingSubtitle;
+ (id)keyPathsForValuesAffectingImage;
+ (id)keyPathsForValuesAffectingName;
+ (id)_mainQueueName;
@property(retain, nonatomic) DBGMemoryDataProcessWrapper *memoryDataGroup; // @synthesize memoryDataGroup=_memoryDataGroup;
@property(copy, nonatomic) NSString *filterString; // @synthesize filterString=_filterString;
@property(retain, nonatomic) DBGViewDebuggerAdditionUIController *viewDebuggingUIController; // @synthesize viewDebuggingUIController=_viewDebuggingUIController;
@property(nonatomic) BOOL showsPendingBlocks; // @synthesize showsPendingBlocks=_showsPendingBlocks;
@property(nonatomic) BOOL showsOnlyAncestorWithInterestingFrames; // @synthesize showsOnlyAncestorWithInterestingFrames=_showsOnlyAncestorWithInterestingFrames;
@property(nonatomic) BOOL showsCompressedStackFrames; // @synthesize showsCompressedStackFrames=_showsCompressedStackFrames;
@property(nonatomic) int navigatorContentMode; // @synthesize navigatorContentMode=_navigatorContentMode;
//- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)invalidateChildItems;
- (id)childRepresentedObjects;
- (void)findInterestingThreads:(id *)arg1 filteredInterestingThreads:(id *)arg2 fromThreads:(id)arg3;
- (id)_generateQueueChildrenFromFilteredInterestingThreads:(id)arg1;
- (BOOL)isLeaf;
- (id)subtitle;
- (id)image;
- (id)name;
- (id)initWithRepresentedObject:(id)arg1;

@end

