/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

//#import "DVTInvalidation-Protocol.h"
//#import "IDEDebugProcess-Protocol.h"

@class DBGDebugSession, DBGStackFrame, DBGThread, DVTObservingToken, DVTStackBacktrace, IDELaunchSession, NSArray, NSMutableArray, NSMutableSet, NSString;

@interface DBGProcess : NSObject /*<IDEDebugProcess, DVTInvalidation>*/
{
    NSString *_associatedProcessUUID;
    NSMutableSet *_threadsAutoRefreshStackFrames;
    DBGThread *_currentThread;
    DBGStackFrame *_currentStackFrame;
    NSMutableArray *_memoryDatas;
    DVTObservingToken *_currentStackFrameValidityObserver;
    DVTStackBacktrace *_currentStackFrameBacktraceWhenSet;
    BOOL _threadsAutoRefreshStackFramesDone;
    int _controlState;
    int _PID;
    DBGDebugSession *_parentDebugSession;
    NSArray *_threads;
    NSArray *_queues;
    NSString *_name;
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingThreads;
+ (void)initialize;
@property(nonatomic) BOOL threadsAutoRefreshStackFramesDone; // @synthesize threadsAutoRefreshStackFramesDone=_threadsAutoRefreshStackFramesDone;
@property(nonatomic) int PID; // @synthesize PID=_PID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSArray *queues; // @synthesize queues=_queues;
@property(copy, nonatomic) NSArray *threads; // @synthesize threads=_threads;
@property(nonatomic) int controlState; // @synthesize controlState=_controlState;
@property(readonly) DBGDebugSession *parentDebugSession; // @synthesize parentDebugSession=_parentDebugSession;
@property(readonly, copy) NSString *associatedProcessUUID; // @synthesize associatedProcessUUID=_associatedProcessUUID;
//- (void).cxx_destruct;
- (void)primitiveInvalidate;
@property(readonly, nonatomic) unsigned long long addressByteSize;
- (void)removeMemoryData:(id)arg1;
- (void)autoUpdateAllMemoryDatas;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 progressHandler:(id)arg3 resultHandler:(void)arg4;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (void)rawMemoryDataForAddressExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (id)memoryDataForUUID:(id)arg1;
- (id)memoryDataForAddressOfExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2;
@property(retain, nonatomic) DBGStackFrame *currentStackFrame; // @synthesize currentStackFrame=_currentStackFrame;
@property(retain, nonatomic) DBGThread *currentThread; // @synthesize currentThread=_currentThread;
- (void)deregisterThreadAutoRefreshesStackFrames:(id)arg1;
- (void)registerThreadAutoRefreshesStackFrames:(id)arg1;
- (BOOL)_shouldSelectFirstSymbolFrame;
- (BOOL)_shouldLookForStackFrameWithDebugSymbols;
- (void)setInitialCurrentStackFrame;
- (BOOL)isPaused;
@property(readonly) NSString *displayStatus;
@property(readonly) IDELaunchSession *launchSession;
- (id)initWithDebugSession:(id)arg1;
- (id)contentDelegateUIExtensionIdentifier;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic) NSArray *loadedCodeModules;
@property(readonly, nonatomic) NSArray *memoryDatas; // @dynamic memoryDatas;
@property(retain) NSMutableArray *mutableMemoryDatas; // @dynamic mutableMemoryDatas;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

