/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
#import <Cocoa/Cocoa.h>
//#import "IDEVariablesViewContentProvider-Protocol.h"
//#import "IDEVariablesViewContextMenuDelegate-Protocol.h"

@class DBGDebugSession, DBGStackFrame, DVTNotificationToken, DVTObservingToken, DVTStackBacktrace, IDEVariablesView, NSButton, NSMutableArray, NSMutableDictionary, NSMutableSet, NSOrderedSet, NSString;

@interface DBGVariablesViewContentProvider : NSObject /*<IDEVariablesViewContextMenuDelegate, IDEVariablesViewContentProvider>*/
{
    IDEVariablesView *_variablesView;
    NSButton *_printDescriptionButton;
    BOOL _requestedAutos;
    BOOL _autosIndexQueryFailed;
    unsigned long long _generation;
    NSMutableArray *_expressions;
    NSMutableDictionary *_variablesAskedForByNameToDataValue;
    NSMutableSet *_varialbesBeingAskedForByName;
    NSOrderedSet *_autosSymbols;
    DVTObservingToken *_framePointerObserverToken;
    DVTObservingToken *_returnValueObserverToken;
    DVTObservingToken *_returnValueIsValidObserverToken;
    DVTObservingToken *_argumentsObserverToken;
    DVTObservingToken *_localsObserverToken;
    DVTObservingToken *_fileStaticsObserverToken;
    DVTObservingToken *_registersObserverToken;
    DVTNotificationToken *_outlineViewSelectionObserver;
    DVTNotificationToken *_outlineViewDidHideObserver;
    DVTNotificationToken *_outlineViewDidUnhideObserver;
    BOOL _loadingNewVariablesInBackground;
    DBGDebugSession *_debugSession;
}

+ (id)_createOptionsDictionaryFromOptionsElement:(id)arg1;
+ (void)initialize;
@property BOOL loadingNewVariablesInBackground; // @synthesize loadingNewVariablesInBackground=_loadingNewVariablesInBackground;
@property(retain) DBGDebugSession *debugSession; // @synthesize debugSession=_debugSession;
//- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)provideHelpMenuItem:(id)arg1;
- (void)providePrimaryMenuItems:(id)arg1;
- (void)quickLookProviderForDataValue:(id)arg1 quickLookProviderHandler:(id)arg2;
- (void)newRootFromChildrenWasInstalled;
- (void)nodeWasDoubleClicked:(id)arg1 row:(long long)arg2 column:(long long)arg3;
- (id)scopePopUpTitleForScopeItem:(long long)arg1;
- (void)_handleSelectedScopeChange;
- (id)contextNameForNode:(id)arg1;
- (id)imageForNode:(id)arg1;
- (BOOL)deleteNode:(id)arg1;
- (id)_createPrintDescriptionButton;
- (void)provideScopeChoices:(id)arg1;
- (void)providerWasInstalledForVariablesView:(id)arg1;
@property(readonly) BOOL supportsShowingRawValues;
@property(readonly) id nodeSortComparator;
@property(readonly) id /*<IDEVariablesViewContextMenuDelegate>*/ contextMenuDelegate;
- (void)_addHelpMenuToMenu:(id)arg1;
- (void)_addViewMemoryOfVariableMenuItemToMenu:(id)arg1 selectedVariable:(id)arg2;
- (void)_addWatchVariableMenuItemToMenu:(id)arg1 selectedVariable:(id)arg2;
- (void)_addDeleteExpressionMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addAddOrEditExpressionMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addEditSummaryFormatMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addEditValueMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addViewValueAsCustomTypeMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addViewValueAsMenuToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addCopyMenuItemToMenu:(id)arg1 selectedVariables:(id)arg2;
- (void)_addPrintDescriptionMenuItemToMenu:(id)arg1 selectedVariable:(id)arg2;
- (void)_addOrEditExpressionAtRow:(long long)arg1;
- (void)_editSummaryFormatAtRow:(long long)arg1;
- (BOOL)_expressionIsForAllStackFrames:(id)arg1;
- (void)_unpersistExpressionString:(id)arg1;
- (void)_persistExpressionString:(id)arg1 forAllStackFrames:(BOOL)arg2;
- (void)_deleteExpressionNode:(id)arg1;
- (id)_addExpressionNode:(id)arg1 forAllStackFrames:(BOOL)arg2;
- (id)_addExpressionNodeToBackingArray:(id)arg1;
- (id)_customExpressions;
- (unsigned long long)_convertCurrentStackFramesLineNumberToEditorDocumentLineNumber:(id)arg1;
- (id)_locationToUseForAutoSymbolsRequestInEditorDocument:(id)arg1;
- (void)_handleAutosIndexQuerySucceeded:(id)arg1;
- (void)_handleAutosIndexQueryFailed;
- (void)_asyncronouslyQueryIndexForSymbolsStartingOnMainThread:(id)arg1 currentGeneration:(unsigned long long)arg2;
- (BOOL)_updateAutoValues;
- (void)_addReturnValueNodeIfNecessary:(id)arg1;
- (void)_updateFilteredList;
- (id)_wrapOrFetchDataValueWithName:(id)arg1 symbolKind:(id)arg2 asNodeType:(unsigned long long)arg3;
- (id)_wrapDataValueWithName:(id)arg1 fromListOfDataValues:(id)arg2 asNodeType:(unsigned long long)arg3;
- (id)_createVariableNodesFromDataValues:(id)arg1 type:(unsigned long long)arg2;
- (id)_createNodeFromIndexSymbol:(id)arg1;
- (id)_manualVariablesList;
- (id)_autoVariablesList;
- (void)_filteredListNeedsUpdatingImmediately;
- (void)_filteredListNeedsUpdating;
@property(readonly) NSString *contextNameForCurrentStackFrame;
@property(readonly) NSString *globalContextName;
- (id)_contextMenuSelectedValues;
- (void)changeDataValueFormat:(id)arg1;
- (void)viewPointeeInMemoryBrowser:(id)arg1;
- (void)viewInMemoryBrowser:(id)arg1;
- (void)editValue:(id)arg1;
- (void)watchVariable:(id)arg1;
- (void)deleteExpressions:(id)arg1;
- (void)addOrEditExpression:(id)arg1;
- (void)editSummaryFormat:(id)arg1;
- (void)viewValueAsCustomType:(id)arg1;
- (void)printDescriptionFromButton:(id)arg1;
- (void)printDescription:(id)arg1;
@property(readonly) BOOL showsRegisters;
@property(readonly) BOOL showsFileStatics;
@property(readonly) BOOL showsArguments;
@property(readonly) BOOL showsLocals;
@property(readonly) BOOL showsAutos;
@property(readonly) DBGStackFrame *currentStackFrame;
- (void)_handleCurrentStackFrameFramePointerChanged;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

