/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class DVTFileDataType;

@interface DVTAnnotationContext : NSObject
{
    DVTFileDataType *_fileDataType;
}

@property(copy) DVTFileDataType *fileDataType; // @synthesize fileDataType=_fileDataType;
//- (void).cxx_destruct;
- (id)description;
- (id)initWithFileDataType:(id)arg1;
- (id)init;

@end

