//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Cocoa/Cocoa.h>

//#import "DVTInvalidation.h"

@class NSArray;
@class DVTAnnotationContext;

@protocol DVTAnnotationManagerDelegate <NSObject>
- (void)didRemoveAnnotations:(NSArray *)arg1;
- (void)didInsertAnnotations:(NSArray *)arg1;
@end



@class DVTStackBacktrace, NSMutableArray, NSString;

@interface DVTAnnotationManager : NSObject /*<DVTInvalidation>*/
{
    id <DVTAnnotationManagerDelegate> _delegate;
    NSMutableArray *_annotationProviders;
}

+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
+ (void)initialize;
@property(retain) id <DVTAnnotationManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) DVTAnnotationContext *context; // @synthesize context=_context;
@property(retain) NSMutableArray *annotationProviders; // @synthesize annotationProviders=_annotationProviders;
//- (void).cxx_destruct;
- (void)removeAllAnnotationProviders;
- (void)setupAnnotationProvidersWithContext:(id)arg1;
- (id)_installObservationBlockForAnnotationProvider:(id)arg1;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

