/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class NSMutableSet, NSSet;

@interface DVTAnnotationProvider : NSObject
{
    NSMutableSet *_annotations;
}

+ (id)annotationProviderForContext:(id)arg1 error:(id *)arg2;
+ (void)initialize;
//- (void).cxx_destruct;
- (void)providerWillUninstall;
- (id)init;

// Remaining properties
@property(copy) NSSet *annotations; // @dynamic annotations;
@property(readonly, copy) NSMutableSet *mutableAnnotations; // @dynamic mutableAnnotations;

@end

