/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSButton.h"

//#import "DVTGradientStyleButton-Protocol.h"

#import <Cocoa/Cocoa.h>

@class NSString;

@interface DVTGradientImageButton : NSButton /*<DVTGradientStyleButton>*/
{
}

+ (Class)cellClass;
@property int highlightSides;
@property int borderSides;
@property int gradientStyle;
@property BOOL showsState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

