/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEBuildIssueAnnotation.h"

@interface IDEBuildIssueStaticAnalyzerWarningAnnotation : IDEBuildIssueAnnotation
{
}

+ (unsigned long long)scrollbarMarkerType;
+ (id)editedTheme;
+ (id)focusedTheme;
+ (id)normalTheme;
+ (id)sidebarIcon;
+ (double)precedence;
- (id)annotationDisplayName;

@end

