/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIndexCollection.h"
#import <sqlite3.h>

@class IDEIndexSymbol;

@interface IDEIndexSymbolOccurrenceCollection : IDEIndexCollection
{
    IDEIndexSymbol *_correspondingSymbol;
}

@property(retain, nonatomic) IDEIndexSymbol *correspondingSymbol; // @synthesize correspondingSymbol=_correspondingSymbol;
//- (void).cxx_destruct;
- (id)instantiateRow:(struct sqlite3_stmt *)arg1;
- (id)tempTableSchema;

@end

