/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIndexDBSQLStream.h"
#import <sqlite3.h>

@class IDEIndexDatabase, NSMutableSet, NSObject/*<OS_dispatch_queue>*/;

@interface IDEIndexDBConnection : IDEIndexDBSQLStream
{
    IDEIndexDatabase *_database;
    NSObject<OS_dispatch_queue> *_runQueue;
    struct sqlite3 *_dbHandle;
    id _cancelCallback;
    long long _tempTableCount;
    NSMutableSet *_tempTables;
    BOOL _closing;
    void *_checkpointInfo;
    int _inUseCount;
    int _collectionCount;
}

+ (void)initialize;
- (id)database;
//- (void).cxx_destruct;
- (void)dealloc;
- (void)close;
- (void)wait;
- (void)reportSQLiteError:(int)arg1 function:(id)arg2 message:(const char *)arg3 info:(id)arg4;
- (void)finalizeSQLiteStmt:(struct sqlite3_stmt **)arg1;
- (void)runSQLiteStmt:(struct sqlite3_stmt **)arg1 sql:(id)arg2 bindings:(id)arg3 forEachRow:(void)arg4 whenDone:(id)arg5;
- (void)cancelWhen:(id)arg1;
- (BOOL)shouldCancel;
- (void)shutdown;
- (void)runSQLite:(id)arg1;
- (void)willSubmitTransaction:(id)arg1;
- (void)explainQueryPlan:(id)arg1;
- (int)doSQLChanges:(id)arg1 withBindings:(id)arg2;
- (void)doSQLQuery:(id)arg1 withBindings:(id)arg2 forEachRow:(void)arg3;
- (void)didDropTempTable:(id)arg1;
- (void)didCreateTempTable:(id)arg1;
- (id)newTempTableWithName:(id)arg1 schema:(id)arg2;
- (id)newTempTableWithSchema:(id)arg1;
- (id)newTempTableName;
- (void)doBlock:(id)arg1;
- (id)dbConnection;
- (void)setAutoCheckpointThreshold:(int)arg1;
- (id)initWithDatabase:(id)arg1 create:(BOOL)arg2 backgroundPriority:(BOOL)arg3;

@end

