/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IDEIndexContainerSymbol.h"

@class IDEIndexCollection;

@interface IDEIndexClassSymbol : IDEIndexContainerSymbol
{
    IDEIndexCollection *_subClasses;
}

//- (void).cxx_destruct;
- (id)allInterfaces;
- (id)interfaces;
- (id)allProtocols;
- (id)protocols;
- (id)allOccurrencesOfMembers:(id)arg1;
- (id)allSubclasses;
- (id)subclasses;
- (id)allSuperclasses;
- (id)superclasses;
- (id)categories;
- (id)ibOutletCollectionProperties;
- (id)ibOutletCollectionVariables;
- (id)ibOutletCollections;
- (id)ibOutletProperties;
- (id)ibOutletVariables;
- (id)ibOutlets;
- (id)ibActionMethods;
- (id)properties;
- (id)instanceVariables;
- (id)classVariables;
- (id)instanceMethods;
- (id)classMethods;

@end

