//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "DVTInvalidation.h"
//#import "IDEDebugNavigableModel.h"
#import <Cocoa/Cocoa.h>
@class DVTStackBacktrace, IDECodeModule, IDELaunchSession, IDEThread, NSNumber, NSString, NSURL;

@interface IDEStackFrame : NSObject /*<IDEDebugNavigableModel, DVTInvalidation>*/
{
    BOOL _hasSymbols;
    BOOL _recorded;
    BOOL _causedCrash;
    NSString *_associatedProcessUUID;
    NSString *_displayName;
    NSString *_filePath;
    IDEThread *_parentThread;
    NSString *_name;
    NSNumber *_frameNumber;
    NSNumber *_framePointer;
    NSURL *_fileURL;
    NSNumber *_lineNumber;
    IDECodeModule *_module;
}

+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)compressedStackFrames:(id)arg1 usingCompressionValue:(long long)arg2;
+ (void)initialize;
@property(nonatomic, getter=hasCausedCrash) BOOL causedCrash; // @synthesize causedCrash=_causedCrash;
@property(nonatomic, getter=isRecorded) BOOL recorded; // @synthesize recorded=_recorded;
@property(retain, nonatomic) IDECodeModule *module; // @synthesize module=_module;
@property(copy, nonatomic) NSNumber *lineNumber; // @synthesize lineNumber=_lineNumber;
@property(copy, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(nonatomic) BOOL hasSymbols; // @synthesize hasSymbols=_hasSymbols;
@property(copy, nonatomic) NSNumber *framePointer; // @synthesize framePointer=_framePointer;
@property(copy, nonatomic) NSNumber *frameNumber; // @synthesize frameNumber=_frameNumber;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) IDEThread *parentThread; // @synthesize parentThread=_parentThread;
@property(readonly, copy) NSString *associatedProcessUUID; // @synthesize associatedProcessUUID=_associatedProcessUUID;
//- (void).cxx_destruct;
- (void)primitiveInvalidate;
@property(readonly, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithParentThread:(id)arg1 frameNumber:(id)arg2 framePointer:(id)arg3 name:(id)arg4;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

