/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
//#import "NSObject.h"

//#import "NSCopying-Protocol.h"
//#import "NSPasteboardWriting-Protocol.h"

@class DVTObservingToken, DVTPointerArray, NSArray, NSMutableArray, NSPredicate, NSString;

@interface IDEVariablesViewNode : NSObject /*<NSPasteboardWriting, NSCopying>*/
{
    IDEVariablesViewNode *_parent;
    DVTObservingToken *_childObserver;
    DVTObservingToken *_childValuesCountValidObserver;
    DVTPointerArray *_childrenPointerArray;
    NSMutableArray *_filteredChildren;
    BOOL _expanded;
    id <IDEDataValue> _dataValue;
    unsigned long long _type;
    NSPredicate *_childFilter;
    NSString *_placeholderStringForNilDataValue;
    NSArray *_childSortDescriptors;
    NSString *_manuallySetName;
}

+ (id)keyPathsForValuesAffectingNumberOfChildren;
+ (id)keyPathsForValuesAffectingChildValuesCountValid;
+ (id)keyPathsForValuesAffectingHasChildren;
+ (id)keyPathsForValuesAffectingName;
+ (id)rootWithChildren:(id)arg1;
+ (void)initialize;
@property(copy) NSString *manuallySetName; // @synthesize manuallySetName=_manuallySetName;
@property(copy, nonatomic) NSArray *childSortDescriptors; // @synthesize childSortDescriptors=_childSortDescriptors;
@property(copy) NSString *placeholderStringForNilDataValue; // @synthesize placeholderStringForNilDataValue=_placeholderStringForNilDataValue;
@property(nonatomic) BOOL expanded; // @synthesize expanded=_expanded;
@property(retain, nonatomic) NSPredicate *childFilter; // @synthesize childFilter=_childFilter;
@property(readonly) unsigned long long type; // @synthesize type=_type;
@property(readonly) id <IDEDataValue> dataValue; // @synthesize dataValue=_dataValue;
@property __weak IDEVariablesViewNode *parent; // @synthesize parent=_parent;
//- (void).cxx_destruct;
- (long long)compareType:(id)arg1;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (void)_ensureChildrenAreValid:(id)arg1;
- (void)recursivleyRestoreExpansionStateAndLoadChildrenUsingContextState:(id)arg1 completionHandler:(id)arg2;
- (id)objectInChildrenProxyAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfChildrenProxy;
- (void)_dataValueChildValuesChanged:(id)arg1;
@property(readonly) NSArray *children;
- (id)_childVariableNodeForChildDataValue:(id)arg1;
- (void)_calculateAndSetFilteredChildren;
- (void)_setFilteredChildrenToNilTriggeringKVO;
@property(readonly) NSArray *filteredChildren;
- (void)setChildren:(id)arg1;
- (BOOL)shouldShowAsFilteredChild;
@property(readonly) long long numberOfChildren;
@property(readonly) BOOL childValuesCountValid;
@property(readonly) BOOL hasChildren;
@property(readonly) BOOL isTopLevelNode;
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly) NSString *fullNamePath;
- (void)overrideDefaultName:(id)arg1;
@property(readonly) NSString *name;
- (void)setDataValue:(id)arg1;
- (void)cleanup;
- (id)initWithDataValue:(id)arg1 type:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

@interface IDEVariableViewRootNode : IDEVariablesViewNode
{
}

- (long long)numberOfChildren;
- (BOOL)childValuesCountValid;
- (BOOL)hasChildren;
- (id)name;
- (void)removeChildnode:(id)arg1;
- (void)addChildNode:(id)arg1;
- (id)initWithChildren:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

